email_support: bot.zakupki@yandex.ru
trial_period_days: 14
query_limits:
  max_queries_in_trial_period: 3
  max_queries_in_common_period: 5
search_parameters:
  base_url: "https://zakupki.gov.ru/epz/order/extendedsearch/results.html?"
  publish_delta: -1
  close_delta: 5
paths:
  to_migrations: "bot_zakupki/storage/migrations"
  to_price_table: "/app/bot_zakupki/static/price.png"
  to_bot_logs: "/app/logs/bot/"
  to_cron_logs: "/app/logs/crons/"
  to_db: "/app/db/bot.sqlite"
production:
  price:
    30:
      1: 30100
      5: 30500
    90:
      1: 90100
      5: 90500
    180:
      1: 18100
      5: 18500
debugging:
  price:
    30:
      1: 30100
      5: 30500
    90:
      1: 90100
      5: 90500
    180:
      1: 18100
      5: 18500
really_production:
  price:
    price:
      30:
        1: 199900
        5: 499900
      90:
        1: 499900
        5: 1249900
      180:
        1: 899900
        5: 2149900
testing:
  paths:
    to_bot_logs: "/app/tests/logs/bot/"
    to_cron_logs: "/app/tests/logs/crons/"
    to_db: "/app/tests/db/bot_test.sqlite"
